amcl:
  ros__parameters:
    use_sim_time: true
    global_frame_id: map 
    odom_frame_id: odom
    base_frame_id: base_footprint
    scan_topic: scan
    min_particles: 100
    max_particles: 500
    laser_max_beams: 30
    update_min_d: 0.05
    update_min_a: 0.1
    odom_model_type: diff
    laser_model_type: likelihood_field
    z_hit: 0.8
    z_rand: 0.2
    sigma_hit: 0.2
    odom_alpha1: 0.2
    odom_alpha2: 0.2
    odom_alpha3: 0.2
    odom_alpha4: 0.2

amcl:
  ros__parameters:
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2
    base_frame_id: "base_footprint"
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.9
    beam_skip_threshold: 0.3
    do_beamskip: false
    global_frame_id: "map"
    lambda_short: 0.1
    laser_likelihood_max_dist: 2.0
    laser_max_range: 4.0
    laser_min_range: 0.05
    laser_model_type: "likelihood_field"
    max_beams: 300
    max_particles: 400
    min_particles: 100
    odom_frame_id: "odom"
    pf_err: 0.05
    pf_z: 0.99
    recovery_alpha_fast: 0.0
    recovery_alpha_slow: 0.0
    resample_interval: 1
    robot_model_type: "nav2_amcl::DifferentialMotionModel"
    save_pose_rate: 0.5
    sigma_hit: 0.2
    tf_broadcast: true
    transform_tolerance: 1.0
    update_min_a: 0.04
    update_min_d: 0.04
    z_hit: 0.5  # How much to trust sensor readings that match the map perfectly. A weight of 0.5 means 50% importance.
    z_max: 0.05 # How much to trust maximum-range readings (when the sensor doesnâ€™t see anything in range)
    z_rand: 0.5 # How much to expect random, unexplainable sensor readings.
    z_short: 0.05
    scan_topic: scan
    map_topic: map
    set_initial_pose: true  
    always_reset_initial_pose: false
    first_map_only: false
    initial_pose:
      x: 2.7
      y: 0.5
      z: 0.0
      yaw: 1.5708